name: 'drafter'
on:
  push:
    branches:
      - master

jobs:
  run:
    name: 'release/update'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
